project:
  type: book

book:
  title: "Advanced R Workbook"
  author: "Nghia Nguyen (Mitchell)"
  date: today
  chapters:
    - index.qmd
    - 1_chapter2.qmd
    - 2_chapter3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lumen

editor: visual

